tasks:
  - name: Dash
    before: |
      pyenv versions
      "yes" | pyenv install 3.11
      pyenv global 3.11
      pyenv version
      python -V
      pyenv which pip 
      pip install --upgrade pip
      python -m venv env
      


vscode:
  extensions:
    - phil294.git-log--graph
    - mhutchie.git-graph
    - phil294.git-log--graph
    - almenon.arepl